POST http://127.0.0.1:5000/summarize HTTP/1.1
content-type: application/json

{
    "original_text": "回りくどい文章は多くの場合、文末に余計な表現が入ることで生じるようです。逆にいえば、文末表現に気を付けることで冗長表現の大部分は防げるということになります。ただ、そのためには冗長な文末表現とはどのようなものかを知ることが大切だと考えられます。たとえば、以下は冗長な文章の典型例だといえるでしょう"
}